/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 *
 * Run `npm run generate-api` to regenerate.
 */

export interface paths {
  '/users/': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['UserResponse'][]
          }
        }
      }
    }
    post: {
      requestBody: {
        content: {
          'application/json': components['schemas']['UserCreateParams']
        }
      }
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['UserResponse']
          }
        }
      }
    }
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    UserResponse: {
      id: number
      name: string
      email: string
      created_at: string
    }
    UserCreateParams: {
      name: string
      email: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type operations = Record<string, never>
