/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 *
 * Run `npm run generate-api` to regenerate.
 */

export interface paths {
  // API エンドポイントがここに生成される
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    // スキーマがここに生成される
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type operations = Record<string, never>
